# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install --prefix frontend
      npm install --prefix backend
    displayName: "Install frontend and backend dependencies"

  - script: |
      npm run test --prefix backend
    displayName: "Backend API tests"

  - script: |
      npm run test:e2e --prefix frontend
    displayName: "Frontend e2e tests"
