# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Install Node.js"

  - script: |
      cd frontend
      npm install
    displayName: "npm install"

  - script: |
      cd frontend
      npm run test:e2e
    displayName: "frontend e2e test"

  - script: |
      pm2 stop api-server
    displayName: "stop serving backend"
