# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install --prefix frontend
      npm install --prefix backend
    displayName: "Install frontend and backend dependencies"

  - script: |
      set DB_PASS=%DB_PASS%
      npm run test --prefix backend
    env:
      DB_URI: $(DB_URI)
      DB_USER: $(DB_USER)
      DB_PASS: $(DB_PASS)
    displayName: "Backend API tests"

  - script: |
      npm run test:e2e --prefix frontend
    displayName: "End-to-end tests"
